### Lista todas las ciudades
GET http://localhost:3000/api/clima
Accept: application/json

### Obtener clima de una ciudad
GET http://localhost:3000/api/clima/Mar%20del%20Plata
Accept: application/json

### Crear nueva ciudad
POST http://localhost:3000/api/clima/crear
Content-Type: application/json

{
  "ciudad": "Avellaneda",
  "temp": 20,
  "viento": 45
}

### Actualizar ciudad (ejemplo: cambiar temp)
PUT http://localhost:3000/api/clima/actualizar/Avellaneda
Content-Type: application/json

{
  "temp": 25,
  "viento": 10
}

### Eliminar ciudad
DELETE http://localhost:3000/api/clima/eliminar/Mar%20del%20Plata
Accept: application/json
